In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_excel("Online retail.xlsx")

In [3]:
data

     shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
0                                burgers,meatballs,eggs
1                                               chutney
2                                        turkey,avocado
3     mineral water,milk,energy bar,whole wheat rice...
4                                        low fat yogurt
...                                                 ...
7495                      butter,light mayo,fresh bread
7496  burgers,frozen vegetables,eggs,french fries,ma...
7497                                            chicken
7498                                 escalope,green tea
7499    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7500 rows x 1 columns]

In [4]:
data.isnull().sum()

shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil    0
dtype: int64

#### Preprocessing The Data

In [6]:
!pip install mlxtend

Requirement already satisfied: mlxtend in c:\users\user\anaconda3\lib\site-packages (0.23.1)
Requirement already satisfied: scipy>=1.2.1 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.13.1)
Requirement already satisfied: numpy>=1.16.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.26.4)
Requirement already satisfied: pandas>=0.24.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (2.2.2)
Requirement already satisfied: scikit-learn>=1.0.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: matplotlib>=3.0.0 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (3.8.4)
Requirement already satisfied: joblib>=0.13.2 in c:\users\user\anaconda3\lib\site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (23.2)
Requirement already satisfied: pillow>=8 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\lib\site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\lib\site-packages (from pandas>=0.24.2->mlxtend) (2023.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\user\anaconda3\lib\site-packages (from scikit-learn>=1.0.2->mlxtend) (2.2.0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)

In [7]:
from mlxtend.frequent_patterns import association_rules,apriori
from mlxtend.preprocessing import TransactionEncoder

In [8]:
data.duplicated().sum()

2325

In [9]:
data.drop_duplicates(inplace=True)

In [10]:
data.duplicated().sum()

0

In [11]:
transactions = data.iloc[:, 0].str.split(',')
transactions

0                              [burgers, meatballs, eggs]
1                                               [chutney]
2                                       [turkey, avocado]
3       [mineral water, milk, energy bar, whole wheat ...
4                                        [low fat yogurt]
                              ...
7492    [burgers, salmon, pancakes, french fries, froz...
7493    [turkey, burgers, dessert wine, shrimp, pasta,...
7495                    [butter, light mayo, fresh bread]
7496    [burgers, frozen vegetables, eggs, french frie...
7499    [eggs, frozen smoothie, yogurt cake, low fat y...
Name: shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil, Length: 5175, dtype: object

In [12]:
te=TransactionEncoder()
te_data=te.fit(transactions).transform(transactions)
df_encoded=pd.DataFrame(te_data,columns=te.columns_)
df_encoded

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5170,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5171,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

### Apriori Algorithm

In [14]:
frequent_itemsets=apriori(df_encoded,min_support=0.01,use_colnames=True)
frequent_itemsets

      support                               itemsets
0    0.029179                              (almonds)
1    0.011014                    (antioxydant juice)
2    0.045797                              (avocado)
3    0.012560                                (bacon)
4    0.015459                       (barbecue sauce)
..        ...                                    ...
431  0.014686  (spaghetti, mineral water, olive oil)
432  0.016618   (spaghetti, mineral water, pancakes)
433  0.012367     (shrimp, mineral water, spaghetti)
434  0.010821       (spaghetti, soup, mineral water)
435  0.013527   (spaghetti, mineral water, tomatoes)

[436 rows x 2 columns]

In [32]:
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules.tail(15)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
825,(shrimp),"(spaghetti, mineral water)",0.098744,0.085024,0.012367,0.125245,1.473048,0.003972,1.045979,0.356320
826,(mineral water),"(shrimp, spaghetti)",0.299710,0.030338,0.012367,0.041264,1.360125,0.003274,1.011396,0.378091
827,(spaghetti),"(shrimp, mineral water)",0.229565,0.033430,0.012367,0.053872,1.611491,0.004693,1.021606,0.492523
828,"(spaghetti, soup)",(mineral water),0.020676,0.299710,0.010821,0.523364,1.746235,0.004624,1.469236,0.436362
829,"(spaghetti, mineral water)",(soup),0.085024,0.070918,0.010821,0.127273,1.794649,0.004792,1.064573,0.483934
830,"(soup, mineral water)",(spaghetti),0.033430,0.229565,0.010821,0.323699,1.410054,0.003147,1.139190,0.300865
831,(spaghetti),"(soup, mineral water)",0.229565,0.033430,0.010821,0.047138,1.410054,0.003147,1.014386,0.377459
832,(soup),"(spaghetti, mineral water)",0.070918,0.085024,0.010821,0.152589,1.794649,0.004792,1.079730,0.476587
833,(mineral water),"(spaghetti, soup)",0.299710,0.020676,0.010821,0.036106,1.746235,0.004624,1.016007,0.610232
834,"(spaghetti, mineral water)",(tomatoes),0.085024,0.091981,0.013527,0.159091,1.729612,0.005706,1.079807,0.461035
835,"(spaghetti, tomatoes)",(mineral water),0.029952,0.299710,0.013527,0.451613,1.506832,0.004550,1.276999,0.346742
836,"(mineral water, tomatoes)",(spaghetti),0.034589,0.229565,0.013527,0.391061,1.703487,0.005586,1.265209,0.427765
837,(spaghetti),"(mineral water, tomatoes)",0.229565,0.034589,0.013527,0.058923,1.703487,0.005586,1.025857,0.536021
838,(mineral water),"(spaghetti, tomatoes)",0.299710,0.029952,0.013527,0.045132,1.506832,0.004550,1.015898,0.480310
839,(tomatoes),"(spaghetti, mineral water)",0.091981,0.085024,0.013527,0.147059,1.729612,0.005706,1.072730,0.464567

rules.sort_values('lift',ascending=False)[0:20]

#if lift ratio is high then it is the better association
ie, if the consumer buys mineral water then he buys almonds as well of(2% to 30%)
#if lift ratio is low then it has better associaton because it is greater than 1
ie, if the consumer buys tomatoes then he also buys spaghetti,mineral water at low chances of (8%-9%)

# Interview Questions

### 1.	What is lift and why is it important in Association rules?
#### sol: Lift is a measure which is used to identify the relation between the items in the dataset. It evalutes the strength of an item that how much likely that consequent will occur for the given anticedent(Condition)
1. if lift>1 strong relation
2. if lift=1 both are independent
3. if lift<1 negative relation
#### The formula for calculating lift is:
###### Lift(𝐴→𝐵)=𝑃(𝐴∩𝐵)/𝑃(𝐴)⋅𝑃(𝐵)
​#Where:
P(A∩B) is the probability that both A and B occur together.
P(A) is the probability of A occurring.
P(B) is the probability of B occurring.

### 2.	What is support and Confidence. How do you calculate them?
#### Support helps identify frequently occurring items or patterns in the data, which is useful for identifying relevant itemsets.
Support(A)= Number of transactions containing A / Total number of transactions
#For a rule
 A→B, the support is calculated as:
Suppor(𝐴→𝐵)=Number of transactions containing both 𝐴 and 𝐵 / Total number of transactions
#### Confidence evaluates the predictive strength of a rule, indicating the reliability of using one item to predict another.
Confidence(A→B)=Support(A∩B) / Support(A)
#where:
A∩B represents the transactions that contain both A and B.
Support(A) is the frequency of A in the dataset.

# 3.	What are some limitations or challenges of Association rules mining?
1. High Computational And Complexity (Especially for large data sets requires more memory for huge number of items)
2. It has more number of rules which are not usefull everytime
3. Association rule mining is typically suited for categorical data and struggles with continuous data.
4. Rules that contain rare but valuable items may be missed because they don’t meet minimum support thresholds.